name: Arduino CI

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Arduino CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | BINDIR=/usr/local/bin sh

      - name: Set up Arduino environment
        run: |
          arduino-cli core update-index
          arduino-cli core install arduino:avr
          arduino-cli lib install "ArduinoJson"  # Example of library; adjust as needed

      - name: Compile Arduino code
        run: |
          arduino-cli compile --fqbn arduino:avr:uno ./server/arduino/arduino.ino

      - name: Upload code (Optional)
        run: |
          echo "Skipping upload step in CI environment"
          # Uncomment the following line if you want to attempt upload in CI (not recommended)
          # arduino-cli upload -p /dev/ttyACM0 --fqbn arduino:avr:uno ./server/arduino/arduino.ino

      - name: Run tests (Optional)
        run: echo "No tests specified"

      - name: Success message
        run: echo "Build completed successfully!"
